/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewPupilsTableRouteImport } from './routes/view-pupils-table'
import { Route as AddPupilRouteImport } from './routes/add-pupil'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo.table'
import { Route as PupilsIdIndexRouteImport } from './routes/pupils/$id/index'
import { Route as PupilsIdEditRouteImport } from './routes/pupils/$id/edit'

const ViewPupilsTableRoute = ViewPupilsTableRouteImport.update({
  id: '/view-pupils-table',
  path: '/view-pupils-table',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPupilRoute = AddPupilRouteImport.update({
  id: '/add-pupil',
  path: '/add-pupil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIdIndexRoute = PupilsIdIndexRouteImport.update({
  id: '/pupils/$id/',
  path: '/pupils/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIdEditRoute = PupilsIdEditRouteImport.update({
  id: '/pupils/$id/edit',
  path: '/pupils/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-pupil': typeof AddPupilRoute
  '/view-pupils-table': typeof ViewPupilsTableRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pupils/$id/edit': typeof PupilsIdEditRoute
  '/pupils/$id': typeof PupilsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-pupil': typeof AddPupilRoute
  '/view-pupils-table': typeof ViewPupilsTableRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pupils/$id/edit': typeof PupilsIdEditRoute
  '/pupils/$id': typeof PupilsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-pupil': typeof AddPupilRoute
  '/view-pupils-table': typeof ViewPupilsTableRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pupils/$id/edit': typeof PupilsIdEditRoute
  '/pupils/$id/': typeof PupilsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-pupil'
    | '/view-pupils-table'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pupils/$id/edit'
    | '/pupils/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-pupil'
    | '/view-pupils-table'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pupils/$id/edit'
    | '/pupils/$id'
  id:
    | '__root__'
    | '/'
    | '/add-pupil'
    | '/view-pupils-table'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pupils/$id/edit'
    | '/pupils/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPupilRoute: typeof AddPupilRoute
  ViewPupilsTableRoute: typeof ViewPupilsTableRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PupilsIdEditRoute: typeof PupilsIdEditRoute
  PupilsIdIndexRoute: typeof PupilsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view-pupils-table': {
      id: '/view-pupils-table'
      path: '/view-pupils-table'
      fullPath: '/view-pupils-table'
      preLoaderRoute: typeof ViewPupilsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-pupil': {
      id: '/add-pupil'
      path: '/add-pupil'
      fullPath: '/add-pupil'
      preLoaderRoute: typeof AddPupilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/$id/': {
      id: '/pupils/$id/'
      path: '/pupils/$id'
      fullPath: '/pupils/$id'
      preLoaderRoute: typeof PupilsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/$id/edit': {
      id: '/pupils/$id/edit'
      path: '/pupils/$id/edit'
      fullPath: '/pupils/$id/edit'
      preLoaderRoute: typeof PupilsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPupilRoute: AddPupilRoute,
  ViewPupilsTableRoute: ViewPupilsTableRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PupilsIdEditRoute: PupilsIdEditRoute,
  PupilsIdIndexRoute: PupilsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
