/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PupilsIndexRouteImport } from './routes/pupils/index'
import { Route as PupilsAddRouteImport } from './routes/pupils/add'
import { Route as PupilsIdIndexRouteImport } from './routes/pupils/$id/index'
import { Route as PupilsIdEditRouteImport } from './routes/pupils/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIndexRoute = PupilsIndexRouteImport.update({
  id: '/pupils/',
  path: '/pupils/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsAddRoute = PupilsAddRouteImport.update({
  id: '/pupils/add',
  path: '/pupils/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIdIndexRoute = PupilsIdIndexRouteImport.update({
  id: '/pupils/$id/',
  path: '/pupils/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIdEditRoute = PupilsIdEditRouteImport.update({
  id: '/pupils/$id/edit',
  path: '/pupils/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pupils/add': typeof PupilsAddRoute
  '/pupils': typeof PupilsIndexRoute
  '/pupils/$id/edit': typeof PupilsIdEditRoute
  '/pupils/$id': typeof PupilsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pupils/add': typeof PupilsAddRoute
  '/pupils': typeof PupilsIndexRoute
  '/pupils/$id/edit': typeof PupilsIdEditRoute
  '/pupils/$id': typeof PupilsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pupils/add': typeof PupilsAddRoute
  '/pupils/': typeof PupilsIndexRoute
  '/pupils/$id/edit': typeof PupilsIdEditRoute
  '/pupils/$id/': typeof PupilsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pupils/add'
    | '/pupils'
    | '/pupils/$id/edit'
    | '/pupils/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pupils/add' | '/pupils' | '/pupils/$id/edit' | '/pupils/$id'
  id:
    | '__root__'
    | '/'
    | '/pupils/add'
    | '/pupils/'
    | '/pupils/$id/edit'
    | '/pupils/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PupilsAddRoute: typeof PupilsAddRoute
  PupilsIndexRoute: typeof PupilsIndexRoute
  PupilsIdEditRoute: typeof PupilsIdEditRoute
  PupilsIdIndexRoute: typeof PupilsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/': {
      id: '/pupils/'
      path: '/pupils'
      fullPath: '/pupils'
      preLoaderRoute: typeof PupilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/add': {
      id: '/pupils/add'
      path: '/pupils/add'
      fullPath: '/pupils/add'
      preLoaderRoute: typeof PupilsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/$id/': {
      id: '/pupils/$id/'
      path: '/pupils/$id'
      fullPath: '/pupils/$id'
      preLoaderRoute: typeof PupilsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/$id/edit': {
      id: '/pupils/$id/edit'
      path: '/pupils/$id/edit'
      fullPath: '/pupils/$id/edit'
      preLoaderRoute: typeof PupilsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PupilsAddRoute: PupilsAddRoute,
  PupilsIndexRoute: PupilsIndexRoute,
  PupilsIdEditRoute: PupilsIdEditRoute,
  PupilsIdIndexRoute: PupilsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
